[DEFAULT]
ConnectionType=initiator
ScreenLogShowHeartBeats=N
ScreenLogShowIncoming=N
ScreenLogShowOutgoing=N
ScreenLogShowEvents=N
StartTime=00:00:00
EndTime=00:00:00
UseDataDictionary=N
ReconnectInterval=10
ValidateUserDefinedFields=N
ValidateIncomingMessage=Y
ResetOnLogon=Y
ResetOnLogout=N
ResetOnDisconnect=Y
SocketUseSSL=Y
SocketCAFile=./fix-prime.coinbase.com.pem
SSLEnable=Y
SSLProtocols=Tls12
SocketConnectPort=4198

[SESSION]
BeginString=FIX.4.2
SenderCompID=SVCACCOUNTID
TargetCompID=COIN
HeartBtInt=30000
ReconnectInterval=30
SocketConnectHost=fix.prime.coinbase.com
FileStorePath=./sessions/